FROM node:20-alpine

WORKDIR /app

# Install dependencies first (for caching)
COPY package.json package-lock.json ./
RUN npm install

# We don't COPY the source code here because we will 
# mount it as a volume in docker-compose.

EXPOSE 3003

# Run in development mode
CMD ["npm", "run", "dev"]
